name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Репог checkout хийнэ
      - name: Checkout code
        uses: actions/checkout@v4

      # Python орчин тохируулна
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Dependencies суулгана
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Unit test ажиллуулна
      - name: Run tests
        run: python -m unittest discover -s tests -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Hub-д login хийнэ
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker image-ийг build болон push хийнэ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to server
        run: echo "Deploying to production server (e.g., Heroku, AWS, etc.)"
        # Энд таны deployment script эсвэл командыг оруулна